#!/usr/bin/env zsh
datadir=${XDG_DATA_HOME:-$HOME/.local/share}/windows
mkdir -m 0700 -p $datadir
git -C $datadir init
logfile=$datadir/windows-vms
exec >>$logfile
date=$(date)
echo
echo "# $date"
curl -fsSL https://developer.microsoft.com/en-us/microsoft-edge/api/tools/vms/ | \
    jq -r '.[].software[].files[] | if has("md5") then .url + " " + .md5 else empty end' | \
    while read -r url md5url; do
        if ! grep -q $url $logfile; then
            echo $url >&2
            # Note that $md5url for newer images now return 404, and I can't
            # find MD5 checksums on the web interface
            # (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
            # anymore, so maybe they abandoned those.
            #
            # We simply set $md5 to empty if curl fails.
            md5=$(curl -fsL $md5url) || md5=
            echo $url $md5
        fi
    done
exec >&-
git -C $datadir add --all
git -C $datadir commit --no-verify --no-gpg-sign --message=$date
